apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rank00001/argo-cd-test.git
    targetRevision: main           # watches the "main" branch (prod)
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-prod
  syncPolicy:
    automated:                     # prod also auto-deploys on every push to main
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
